### ISSUE TITLE
Awesome repository!

### ISSUE THREAD

**Issue by gelsas** [Thomasssb1/reddit-2-video#1]
Just found this repository and it seems to have so many great features already. 

I just wanted to ask if there is an example output video, that you could share and if you maybe have a tutorial video where we can see this in action, how it works how fast it is etc.

**Comment by Thomasssb1** [comment]
Sure! I will add an example video to readme as well as how long it took to generate that video.
I just want to let you know that currently the project is in beta, but will be fully releasing very soon - I just want to make the output more optimised for different post types (other than the singular `--type post` option) then I will release version 1.0.
Thanks for your interest!

**Comment by Thomasssb1** [comment]
Sorry for this taking extra time, I have got a working prototype of the release version but it is on my other computer which I do not have access to currently. Hopefully, I will be able to get a hold of it and update the README to contain example output videos, right now I just have example commands as well as explaining what they will do. 
Thanks for your patience.

**Comment by Thomasssb1** [comment]
I have released [v1.0.0](https://github.com/Thomasssb1/reddit-2-video/releases/tag/Release) - it is fairly easy to get started. Regarding an explanation of how it works & timings, I plan to update [WORKINGS.md](https://github.com/Thomasssb1/reddit-2-video/blob/master/WORKINGS.md) more to accommodate those requests - for now I just have a basic overview. Thanks for your patience, if you need any more help, you can always post an issue again.

**Comment by gelsas** [comment]
Nice! I will check it out in the coming days. Should I wait still for the update of the workings.md or should I just try it out?

**Comment by Thomasssb1** [comment]
Just give it a try, I will be periodically updating the workings document but it does not affect functionality. 👍
